#!/bin/bash

#this script requires notify-send.sh from (https://github.com/vlevit/notify-send.sh)
#vanilla notify-send is not able to replace previous notifications
#this script requires 2 picture files for icons, replace the paths below with paths to the files
#this script requires pacmd and pactl

#location of temp file
lastIDfile=/tmp/soundcontrolID

#check if temp file is empty, adds zero if empty
if ! [ -s $lastIDfile ]
then
	echo 0 > $lastIDfile
fi

#icon pictures
speakerPicture=~/.config/soundcontrol/icons8-voice-96-black.png
mutePicture=~/.config/soundcontrol/icons8-mute-96-black.png

#second the notification should stay on screen
time=1

#find the active sink
SINK=$(pacmd list-sinks | grep "index:" | grep '*' | awk '{print $3}')

#if no sink found choose default sink
if [ "$SINK" == "" ]; then
  SINK="0"
fi

#if mute then mute otherwise set 
if [ "$1" != "M" ]; then
  pactl set-sink-volume "$SINK" "$1"
else
  pactl set-sink-mute "$SINK" toggle
fi

#save current volume amount in percent
volume=$(pacmd list-sinks | grep "index: $SINK" -C7 | grep "volume" | awk '{print $5}')

#choose icon based on mute status
if [ "$(pacmd list-sinks | grep 'muted' | awk '{print $2}')" == "yes" ]; then
	icon=$mutePicture
	#icon=" (M)"
else
	icon=$speakerPicture
	#icon=""
fi

#send notification 
notify-send.sh -t $(( 1000*$time )) -i $icon -R $lastIDfile -p "Volume: $volume"
#due to an update noticed on 2020-10-20 the -R option is not working anymore
#Also the notification is appearing differently (Maybe find a different notification daemon)
#notify-send.sh -t $(( 1000*$time )) -i $icon -p "Volume: $volume" 
##uncommenting this causes mutliple notify-send to happen. Need a better fix to remove tmp file
#wait time plus 10 seconds just in case
#sleep "$(( $time+10 ))"s

#remove temp file
#if [ -f $lastIDfile ]; then
#	rm $lastIDfile
#fi
